export type Position = {
  x: number;
  y: number;
};

export type Credentials = {
  name: string; // unique -> id
  password: string;
};

export type RoomUsers = {
  name: string;
  index: number | string;
}[];

export type ShipType = 'small' | 'medium' | 'large' | 'huge';

export type ShipInfo = {
  position: Position;
  direction: boolean;
  length: number;
  type: ShipType;
};

export type AttackStatus = 'miss' | 'killed' | 'shot';

export type CommandType =
  | 'reg'
  | 'update_winners'
  | 'create_room'
  | 'add_user_to_room'
  | 'single_play'
  | 'create_game'
  | 'update_room'
  | 'add_ships'
  | 'start_game'
  | 'attack'
  | 'randomAttack'
  | 'turn'
  | 'finish';

export type CommandRequestWithStringifiedData = {
  type: CommandType;
  data: string; // should be a json string
  id: 0; // should be always 0
};

type Command<T extends CommandType> = Omit<CommandRequestWithStringifiedData, 'data'> & {
  type: T;
};

export type PlayerLoginRequest = Command<'reg'> & {
  data: Credentials;
};

export type PlayerLoginResponse = Command<'reg'> & {
  data: {
    name: string;
    index: number | string; // player id
    error: boolean;
    errorText: string;
  };
};

export type UpdateWinnersResponse = Command<'update_winners'> & {
  data: {
    name: string;
    wins: number;
  }[];
};

export type CreateRoomRequest = Command<'create_room'> & {
  data: '';
};

export type SinglePlayRequest = Command<'single_play'> & {
  data: '';
};

export type AddUserToRoomRequest = Command<'add_user_to_room'> & {
  data: {
    indexRoom: number | string; // room id
  };
};

//send for both players in the room, after they are connected to the room
export type CreateGameResponse = Command<'create_game'> & {
  data: {
    idGame: number | string;
    // id generated by server for player in the game session,
    // not enemy (unique id for every player)
    idPlayer: number | string;
  };
};

export type UpdateRoomResponse = Command<'update_room'> & {
  data: {
    roomId: number | string;
    roomUsers: RoomUsers;
  }[];
};

export type AddShipsRequest = Command<'add_ships'> & {
  data: {
    gameId: number | string;
    // id of the player in the current game session
    indexPlayer: number | string;
    ships: ShipInfo[];
  };
};

export type StartGameResponse = Command<'start_game'> & {
  data: {
    // id of the player in the current game session, who have sent his ships
    currentPlayerIndex: number | string;
    // player's ships, not enemy's
    ships: ShipInfo[];
  };
};

export type AttackRequest = Command<'attack'> & {
  data: {
    gameId: number | string;
    x: number;
    y: number;
    // id of the player in the current game session
    indexPlayer: number | string;
  };
};

export type AttackResponse = Command<'attack'> & {
  data: {
    position: Position;
    // id of the player in the current game session
    currentPlayer: number | string;
    status: AttackStatus;
  };
};

export type RandomAttackRequest = Command<'randomAttack'> & {
  data: {
    gameId: number | string;
    indexPlayer: number | string;
  };
};

export type PlayerTurnResponse = Command<'turn'> & {
  data: {
    // id of the player in the current game session
    currentPlayer: number | string;
  };
};

export type FinishGameResponse = Command<'finish'> & {
  data: {
    // id of the player in the current game session
    winPlayer: number | string;
  };
};

export type CommandRequest<T extends CommandType> = T extends 'reg'
  ? PlayerLoginRequest
  : T extends 'create_room'
    ? CreateRoomRequest
    : T extends 'add_user_to_room'
      ? AddUserToRoomRequest
      : T extends 'add_ships'
        ? AddShipsRequest
        : T extends 'attack'
          ? AttackRequest
          : T extends 'randomAttack'
            ? RandomAttackRequest
            : T extends 'single_play'
              ? SinglePlayRequest
              : never;

export type CommandResponse<T extends CommandType> = T extends 'reg'
  ? PlayerLoginResponse
  : T extends 'update_winners'
    ? UpdateWinnersResponse
    : T extends 'create_game'
      ? CreateGameResponse
      : T extends 'update_room'
        ? UpdateRoomResponse
        : T extends 'start_game'
          ? StartGameResponse
          : T extends 'attack'
            ? AttackResponse
            : T extends 'turn'
              ? PlayerTurnResponse
              : T extends 'finish'
                ? FinishGameResponse
                : never;
